wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693448290.652627
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 69
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 69
      - 103
      - 105
      3:
      - 2
      - 13
      - 15
      - 23
      4: 3.10.10
      5: 0.15.8
      6: 4.26.1
      8:
      - 4
      - 5
